import axios from 'axios';
import dotenv from 'dotenv';
import {someData} from './data_base/someData'

dotenv.config();

const serverUrl = `http://localhost:${process.env.PORT}/api/users`;
// const user = { 
// username: 'Test User',
// age: 30,
// hobbies:['testing'],
// }

const arr = [
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.post(serverUrl, JSON.stringify(someData)),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl+'/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d'),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),
  axios.get(serverUrl),

]
console.time('Time');

const sendReq = async () => {
await Promise.all(arr);


console.timeEnd('Time')
}

console.log('N queries = '+arr.length)
sendReq()